#lang sicp

(define (make-interval lower-bound upper-bound)
  (cons lower-bound upper-bound))
(define (lower-bound interval) (car interval))
(define (upper-bound interval) (cdr interval))

(define (print-interval interval)
  (display "[")
  (display (lower-bound interval))
  (display ", ")
  (display (upper-bound interval))
  (display "]")
  (newline))

(define (mul-interval x y)
  (cond ((>= (lower-bound x) 0)
         (cond ((>= (lower-bound y) 0)
                (make-interval (* (lower-bound x) (lower-bound y))
                               (* (upper-bound x) (upper-bound y))))
               ((<= (upper-bound y) 0)
                (make-interval (* (upper-bound x) (lower-bound y))
                               (* (lower-bound x) (upper-bound y))))
               (else
                (make-interval (* (upper-bound x) (lower-bound y))
                               (* (upper-bound x) (upper-bound y))))))
        ((<= (upper-bound x) 0)
         (cond ((>= (lower-bound y) 0)
                (make-interval (* (lower-bound x) (upper-bound y))
                               (* (upper-bound x) (lower-bound y))))
               ((<= (upper-bound y) 0)
                (make-interval (* (upper-bound x) (upper-bound y))
                               (* (lower-bound x) (lower-bound y))))
               (else
                (make-interval (* (lower-bound x) (upper-bound y))
                               (* (lower-bound x) (lower-bound y))))))
        ((>= (lower-bound y) 0)
         (make-interval (* (lower-bound x) (upper-bound y))
                        (* (upper-bound x) (upper-bound y))))
        ((<= (upper-bound y) 0)
         (make-interval (* (upper-bound x) (lower-bound y))
                        (* (lower-bound x) (lower-bound y))))
        (else
         (make-interval (min (* (lower-bound x) (upper-bound y))
                             (* (upper-bound x) (lower-bound y)))
                        (max (* (lower-bound x) (lower-bound y))
                             (* (upper-bound x) (upper-bound y)))))))

(print-interval (mul-interval (make-interval 3 4)
                              (make-interval 10 20)))
(print-interval (mul-interval (make-interval 3 4)
                              (make-interval -10 20)))
(print-interval (mul-interval (make-interval 3 4)
                              (make-interval -20 -10)))
(print-interval (mul-interval (make-interval 3 4)
                              (make-interval -20 0)))
(print-interval (mul-interval (make-interval 3 4)
                              (make-interval 0 10)))
(newline)

(print-interval (mul-interval (make-interval -4 -3)
                              (make-interval 10 20)))
(print-interval (mul-interval (make-interval -4 -3)
                              (make-interval -10 20)))
(print-interval (mul-interval (make-interval -4 -3)
                              (make-interval -20 -10)))
(print-interval (mul-interval (make-interval -4 -3)
                              (make-interval -20 0)))
(print-interval (mul-interval (make-interval -4 -3)
                              (make-interval 0 10)))
(newline)

(print-interval (mul-interval (make-interval -4 3)
                              (make-interval 10 20)))
(print-interval (mul-interval (make-interval -4 3)
                              (make-interval -10 20)))
(print-interval (mul-interval (make-interval -4 3)
                              (make-interval -20 -10)))
(print-interval (mul-interval (make-interval -4 3)
                              (make-interval -20 0)))
(print-interval (mul-interval (make-interval -4 3)
                              (make-interval 0 10)))
(newline)

(print-interval (mul-interval (make-interval 0 4)
                              (make-interval 10 20)))
(print-interval (mul-interval (make-interval 0 4)
                              (make-interval -10 20)))
(print-interval (mul-interval (make-interval 0 4)
                              (make-interval -20 -10)))
(print-interval (mul-interval (make-interval 0 4)
                              (make-interval -20 0)))
(print-interval (mul-interval (make-interval 0 4)
                              (make-interval 0 10)))
(newline)

(print-interval (mul-interval (make-interval -3 0)
                              (make-interval 10 20)))
(print-interval (mul-interval (make-interval -3 0)
                              (make-interval -10 20)))
(print-interval (mul-interval (make-interval -3 0)
                              (make-interval -20 -10)))
(print-interval (mul-interval (make-interval -3 0)
                              (make-interval -20 0)))
(print-interval (mul-interval (make-interval -3 0)
                              (make-interval 0 10)))
